// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

// Fallback to hardcoded values if env vars are missing (for development)
const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL || 'https://jftthfniwfarxyisszjh.supabase.co';
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY || (() => {
  // Try to get from localStorage (if user has set it manually)
  if (typeof window !== 'undefined') {
    const stored = localStorage.getItem('supabase_anon_key');
    if (stored) return stored;
  }
  // Return empty string - will show error in console
  return '';
})();

// Debug: Log Supabase configuration
if (typeof window !== 'undefined') {
  const hasKey = !!SUPABASE_PUBLISHABLE_KEY && SUPABASE_PUBLISHABLE_KEY.length > 0;
  console.log('[Supabase Client] Configuration:', {
    url: SUPABASE_URL ? SUPABASE_URL.substring(0, 50) + '...' : 'MISSING',
    key: hasKey ? SUPABASE_PUBLISHABLE_KEY.substring(0, 20) + '...' : 'MISSING',
    urlExists: !!SUPABASE_URL,
    keyExists: hasKey,
  });
  
  if (!hasKey) {
    console.error('[Supabase Client] ❌ VITE_SUPABASE_PUBLISHABLE_KEY is missing!');
    console.error('[Supabase Client] Please set it in .env file or run:');
    console.error('[Supabase Client] localStorage.setItem("supabase_anon_key", "YOUR_KEY_HERE")');
    console.error('[Supabase Client] Get your key from: https://supabase.com/dashboard/project/jftthfniwfarxyisszjh/settings/api');
  }
}

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});

// Debug: Test connection on client side
if (typeof window !== 'undefined' && SUPABASE_URL && SUPABASE_PUBLISHABLE_KEY) {
  // Test connection by trying to read from a table
  supabase.from('stop_notification_subscriptions').select('id').limit(1).then(({ error }) => {
    if (error) {
      console.error('[Supabase Client] ❌ Connection test failed:', error);
    } else {
      console.log('[Supabase Client] ✅ Connection test successful');
    }
  }).catch((err) => {
    console.error('[Supabase Client] ❌ Connection test error:', err);
  });
}